builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - main: ./cmd/edge
    id: "edge"
    binary: edge
    goos:
      - linux
      - darwin
      - windows
