builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/edge
    id: "edge"
    binary: edge
    goos:
      - linux
      - darwin
      - windows
    ldflags: -s -w -X main.version={{.Version}} -X "main.installFrom=Binary"
archives:
  - format_overrides:
      - goos: windows
        format: zip
